=begin
#Telstra Programmable Network API

#Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.

OpenAPI spec version: 2.1.2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require "uri"

module TelstraTPN
  class DatacentresApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # Get list of all the data centers
    # Get list of all the data centers
    # @param [Hash] opts the optional parameters
    # @return [Array<Model100InventoryDatacentersResponse>]
    def get_list_of_all_the_data_centers(opts = {})
      data, _status_code, _headers = get_list_of_all_the_data_centers_with_http_info(opts)
      return data
    end

    # Get list of all the data centers
    # Get list of all the data centers
    # @param [Hash] opts the optional parameters
    # @return [Array<(Array<Model100InventoryDatacentersResponse>, Fixnum, Hash)>] Array<Model100InventoryDatacentersResponse> data, response status code and response headers
    def get_list_of_all_the_data_centers_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: DatacentresApi.get_list_of_all_the_data_centers ..."
      end
      # resource path
      local_var_path = "/1.0.0/inventory/datacenters"

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['auth']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<Model100InventoryDatacentersResponse>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DatacentresApi#get_list_of_all_the_data_centers\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
