=begin
#Telstra Programmable Network API

#Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.

OpenAPI spec version: 2.1.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require "uri"

module TelstraTPN
  class LinksApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # Create Link and initial Contract
    # Create Link and initial Contract
    # @param [Hash] opts the optional parameters
    # @option opts [InventoryLinkRequest] :body 
    # @return [InventoryLinkResponse]
    def inventory_link_post(opts = {})
      data, _status_code, _headers = inventory_link_post_with_http_info(opts)
      return data
    end

    # Create Link and initial Contract
    # Create Link and initial Contract
    # @param [Hash] opts the optional parameters
    # @option opts [InventoryLinkRequest] :body 
    # @return [Array<(InventoryLinkResponse, Fixnum, Hash)>] InventoryLinkResponse data, response status code and response headers
    def inventory_link_post_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: LinksApi.inventory_link_post ..."
      end
      # resource path
      local_var_path = "/1.0.0/inventory/link"

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(opts[:'body'])
      auth_names = ['auth']
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'InventoryLinkResponse')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: LinksApi#inventory_link_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get details of specified link
    # Get details of specified link
    # @param linkid Unique identifier representing a specific link
    # @param [Hash] opts the optional parameters
    # @return [InventoryLinksResponse]
    def inventory_links_by_linkid_get(linkid, opts = {})
      data, _status_code, _headers = inventory_links_by_linkid_get_with_http_info(linkid, opts)
      return data
    end

    # Get details of specified link
    # Get details of specified link
    # @param linkid Unique identifier representing a specific link
    # @param [Hash] opts the optional parameters
    # @return [Array<(InventoryLinksResponse, Fixnum, Hash)>] InventoryLinksResponse data, response status code and response headers
    def inventory_links_by_linkid_get_with_http_info(linkid, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: LinksApi.inventory_links_by_linkid_get ..."
      end
      # verify the required parameter 'linkid' is set
      if @api_client.config.client_side_validation && linkid.nil?
        fail ArgumentError, "Missing the required parameter 'linkid' when calling LinksApi.inventory_links_by_linkid_get"
      end
      # resource path
      local_var_path = "/1.0.0/inventory/links/{linkid}".sub('{' + 'linkid' + '}', linkid.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['auth']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'InventoryLinksResponse')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: LinksApi#inventory_links_by_linkid_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get active Links
    # Get active Links
    # @param customeruuid Unique identifier representing a specific customer
    # @param [Hash] opts the optional parameters
    # @return [Array<Link>]
    def inventory_links_customer_by_customeruuid_get(customeruuid, opts = {})
      data, _status_code, _headers = inventory_links_customer_by_customeruuid_get_with_http_info(customeruuid, opts)
      return data
    end

    # Get active Links
    # Get active Links
    # @param customeruuid Unique identifier representing a specific customer
    # @param [Hash] opts the optional parameters
    # @return [Array<(Array<Link>, Fixnum, Hash)>] Array<Link> data, response status code and response headers
    def inventory_links_customer_by_customeruuid_get_with_http_info(customeruuid, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: LinksApi.inventory_links_customer_by_customeruuid_get ..."
      end
      # verify the required parameter 'customeruuid' is set
      if @api_client.config.client_side_validation && customeruuid.nil?
        fail ArgumentError, "Missing the required parameter 'customeruuid' when calling LinksApi.inventory_links_customer_by_customeruuid_get"
      end
      # resource path
      local_var_path = "/1.0.0/inventory/links/customer/{customeruuid}".sub('{' + 'customeruuid' + '}', customeruuid.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['auth']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<Link>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: LinksApi#inventory_links_customer_by_customeruuid_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get Link history
    # Get Link history
    # @param linkid Unique identifier representing a specific link
    # @param [Hash] opts the optional parameters
    # @return [InventoryLinksHistoryResponse]
    def inventory_links_history_by_linkid_get(linkid, opts = {})
      data, _status_code, _headers = inventory_links_history_by_linkid_get_with_http_info(linkid, opts)
      return data
    end

    # Get Link history
    # Get Link history
    # @param linkid Unique identifier representing a specific link
    # @param [Hash] opts the optional parameters
    # @return [Array<(InventoryLinksHistoryResponse, Fixnum, Hash)>] InventoryLinksHistoryResponse data, response status code and response headers
    def inventory_links_history_by_linkid_get_with_http_info(linkid, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: LinksApi.inventory_links_history_by_linkid_get ..."
      end
      # verify the required parameter 'linkid' is set
      if @api_client.config.client_side_validation && linkid.nil?
        fail ArgumentError, "Missing the required parameter 'linkid' when calling LinksApi.inventory_links_history_by_linkid_get"
      end
      # resource path
      local_var_path = "/1.0.0/inventory/links/history/{linkid}".sub('{' + 'linkid' + '}', linkid.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['auth']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'InventoryLinksHistoryResponse')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: LinksApi#inventory_links_history_by_linkid_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
