=begin
#Telstra Programmable Network API

#Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.

OpenAPI spec version: 2.1.2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require "uri"

module TelstraTPN
  class LinksApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # Create Link and initial Contract
    # Create Link and initial Contract
    # @param [Hash] opts the optional parameters
    # @option opts [Model100InventoryLinkRequest] :body 
    # @return [Model100InventoryLinkResponse]
    def create_link_and_initial_contract(opts = {})
      data, _status_code, _headers = create_link_and_initial_contract_with_http_info(opts)
      return data
    end

    # Create Link and initial Contract
    # Create Link and initial Contract
    # @param [Hash] opts the optional parameters
    # @option opts [Model100InventoryLinkRequest] :body 
    # @return [Array<(Model100InventoryLinkResponse, Fixnum, Hash)>] Model100InventoryLinkResponse data, response status code and response headers
    def create_link_and_initial_contract_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: LinksApi.create_link_and_initial_contract ..."
      end
      # resource path
      local_var_path = "/1.0.0/inventory/link"

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(opts[:'body'])
      auth_names = ['auth']
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Model100InventoryLinkResponse')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: LinksApi#create_link_and_initial_contract\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get active Links
    # Get active Links
    # @param customeruuid Unique identifier representing a specific customer
    # @param [Hash] opts the optional parameters
    # @return [Array<Link>]
    def get_active_links(customeruuid, opts = {})
      data, _status_code, _headers = get_active_links_with_http_info(customeruuid, opts)
      return data
    end

    # Get active Links
    # Get active Links
    # @param customeruuid Unique identifier representing a specific customer
    # @param [Hash] opts the optional parameters
    # @return [Array<(Array<Link>, Fixnum, Hash)>] Array<Link> data, response status code and response headers
    def get_active_links_with_http_info(customeruuid, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: LinksApi.get_active_links ..."
      end
      # verify the required parameter 'customeruuid' is set
      if @api_client.config.client_side_validation && customeruuid.nil?
        fail ArgumentError, "Missing the required parameter 'customeruuid' when calling LinksApi.get_active_links"
      end
      # resource path
      local_var_path = "/1.0.0/inventory/links/customer/{customeruuid}".sub('{' + 'customeruuid' + '}', customeruuid.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['auth']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<Link>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: LinksApi#get_active_links\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get details of specified link
    # Get details of specified link
    # @param linkid Unique identifier representing a specific link
    # @param [Hash] opts the optional parameters
    # @return [Model100InventoryLinksResponse]
    def get_details_of_specified_link(linkid, opts = {})
      data, _status_code, _headers = get_details_of_specified_link_with_http_info(linkid, opts)
      return data
    end

    # Get details of specified link
    # Get details of specified link
    # @param linkid Unique identifier representing a specific link
    # @param [Hash] opts the optional parameters
    # @return [Array<(Model100InventoryLinksResponse, Fixnum, Hash)>] Model100InventoryLinksResponse data, response status code and response headers
    def get_details_of_specified_link_with_http_info(linkid, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: LinksApi.get_details_of_specified_link ..."
      end
      # verify the required parameter 'linkid' is set
      if @api_client.config.client_side_validation && linkid.nil?
        fail ArgumentError, "Missing the required parameter 'linkid' when calling LinksApi.get_details_of_specified_link"
      end
      # resource path
      local_var_path = "/1.0.0/inventory/links/{linkid}".sub('{' + 'linkid' + '}', linkid.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['auth']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Model100InventoryLinksResponse')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: LinksApi#get_details_of_specified_link\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get Link history
    # Get Link history
    # @param linkid Unique identifier representing a specific link
    # @param [Hash] opts the optional parameters
    # @return [Model100InventoryLinksHistoryResponse]
    def get_link_history(linkid, opts = {})
      data, _status_code, _headers = get_link_history_with_http_info(linkid, opts)
      return data
    end

    # Get Link history
    # Get Link history
    # @param linkid Unique identifier representing a specific link
    # @param [Hash] opts the optional parameters
    # @return [Array<(Model100InventoryLinksHistoryResponse, Fixnum, Hash)>] Model100InventoryLinksHistoryResponse data, response status code and response headers
    def get_link_history_with_http_info(linkid, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: LinksApi.get_link_history ..."
      end
      # verify the required parameter 'linkid' is set
      if @api_client.config.client_side_validation && linkid.nil?
        fail ArgumentError, "Missing the required parameter 'linkid' when calling LinksApi.get_link_history"
      end
      # resource path
      local_var_path = "/1.0.0/inventory/links/history/{linkid}".sub('{' + 'linkid' + '}', linkid.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['auth']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Model100InventoryLinksHistoryResponse')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: LinksApi#get_link_history\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
