=begin
#Telstra Programmable Network API

#Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.

OpenAPI spec version: 2.4.2
Contact: pnapi-support@team.telstra.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.1.2

=end

require 'uri'

module TelstraTPN
  class LinksApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Create Link and initial Contract
    # @param [Hash] opts the optional parameters
    # @option opts [Createlinkrequest] :createlinkrequest 
    # @return [SuccessFragment]
    def inventory_link(opts = {})
      data, _status_code, _headers = inventory_link_with_http_info(opts)
      data
    end

    # Create Link and initial Contract
    # @param [Hash] opts the optional parameters
    # @option opts [Createlinkrequest] :createlinkrequest 
    # @return [Array<(SuccessFragment, Fixnum, Hash)>] SuccessFragment data, response status code and response headers
    def inventory_link_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: LinksApi.inventory_link ...'
      end
      # resource path
      local_var_path = '/1.0.0/inventory/link'

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(opts[:'createlinkrequest'])
      auth_names = ['oAuth2']
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'SuccessFragment')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: LinksApi#inventory_link\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
    # Get details of specified link
    # @param linkid Unique identifier representing a specific link
    # @param [Hash] opts the optional parameters
    # @return [InlineResponse2007]
    def inventory_links(linkid, opts = {})
      data, _status_code, _headers = inventory_links_with_http_info(linkid, opts)
      data
    end

    # Get details of specified link
    # @param linkid Unique identifier representing a specific link
    # @param [Hash] opts the optional parameters
    # @return [Array<(InlineResponse2007, Fixnum, Hash)>] InlineResponse2007 data, response status code and response headers
    def inventory_links_with_http_info(linkid, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: LinksApi.inventory_links ...'
      end
      # verify the required parameter 'linkid' is set
      if @api_client.config.client_side_validation && linkid.nil?
        fail ArgumentError, "Missing the required parameter 'linkid' when calling LinksApi.inventory_links"
      end
      # resource path
      local_var_path = '/1.0.0/inventory/links/{linkid}'.sub('{' + 'linkid' + '}', linkid.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['oAuth2']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'InlineResponse2007')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: LinksApi#inventory_links\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
    # Get active Links
    # @param customeruuid Unique identifier representing a specific customer
    # @param [Hash] opts the optional parameters
    # @return [Array<Link>]
    def inventory_links_customer(customeruuid, opts = {})
      data, _status_code, _headers = inventory_links_customer_with_http_info(customeruuid, opts)
      data
    end

    # Get active Links
    # @param customeruuid Unique identifier representing a specific customer
    # @param [Hash] opts the optional parameters
    # @return [Array<(Array<Link>, Fixnum, Hash)>] Array<Link> data, response status code and response headers
    def inventory_links_customer_with_http_info(customeruuid, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: LinksApi.inventory_links_customer ...'
      end
      # verify the required parameter 'customeruuid' is set
      if @api_client.config.client_side_validation && customeruuid.nil?
        fail ArgumentError, "Missing the required parameter 'customeruuid' when calling LinksApi.inventory_links_customer"
      end
      # resource path
      local_var_path = '/1.0.0/inventory/links/customer/{customeruuid}'.sub('{' + 'customeruuid' + '}', customeruuid.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['oAuth2']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<Link>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: LinksApi#inventory_links_customer\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
    # Get Link history
    # @param linkid Unique identifier representing a specific link
    # @param [Hash] opts the optional parameters
    # @return [InlineResponse2005]
    def inventory_links_history(linkid, opts = {})
      data, _status_code, _headers = inventory_links_history_with_http_info(linkid, opts)
      data
    end

    # Get Link history
    # @param linkid Unique identifier representing a specific link
    # @param [Hash] opts the optional parameters
    # @return [Array<(InlineResponse2005, Fixnum, Hash)>] InlineResponse2005 data, response status code and response headers
    def inventory_links_history_with_http_info(linkid, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: LinksApi.inventory_links_history ...'
      end
      # verify the required parameter 'linkid' is set
      if @api_client.config.client_side_validation && linkid.nil?
        fail ArgumentError, "Missing the required parameter 'linkid' when calling LinksApi.inventory_links_history"
      end
      # resource path
      local_var_path = '/1.0.0/inventory/links/history/{linkid}'.sub('{' + 'linkid' + '}', linkid.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['oAuth2']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'InlineResponse2005')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: LinksApi#inventory_links_history\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
    # Get statistics for flow
    # Get statistics related to the specified flow
    # @param linkid Unique identifier representing a specific link
    # @param startdate Start date for statistics query
    # @param enddate End date for statistics query
    # @param [Hash] opts the optional parameters
    # @return [Array<InlineResponse20019>]
    def inventory_links_stats_flow(linkid, startdate, enddate, opts = {})
      data, _status_code, _headers = inventory_links_stats_flow_with_http_info(linkid, startdate, enddate, opts)
      data
    end

    # Get statistics for flow
    # Get statistics related to the specified flow
    # @param linkid Unique identifier representing a specific link
    # @param startdate Start date for statistics query
    # @param enddate End date for statistics query
    # @param [Hash] opts the optional parameters
    # @return [Array<(Array<InlineResponse20019>, Fixnum, Hash)>] Array<InlineResponse20019> data, response status code and response headers
    def inventory_links_stats_flow_with_http_info(linkid, startdate, enddate, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: LinksApi.inventory_links_stats_flow ...'
      end
      # verify the required parameter 'linkid' is set
      if @api_client.config.client_side_validation && linkid.nil?
        fail ArgumentError, "Missing the required parameter 'linkid' when calling LinksApi.inventory_links_stats_flow"
      end
      # verify the required parameter 'startdate' is set
      if @api_client.config.client_side_validation && startdate.nil?
        fail ArgumentError, "Missing the required parameter 'startdate' when calling LinksApi.inventory_links_stats_flow"
      end
      # verify the required parameter 'enddate' is set
      if @api_client.config.client_side_validation && enddate.nil?
        fail ArgumentError, "Missing the required parameter 'enddate' when calling LinksApi.inventory_links_stats_flow"
      end
      # resource path
      local_var_path = '/1.0.0/inventory/links-stats/flow/{linkid}/{startdate}/{enddate}'.sub('{' + 'linkid' + '}', linkid.to_s).sub('{' + 'startdate' + '}', startdate.to_s).sub('{' + 'enddate' + '}', enddate.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['oAuth2']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<InlineResponse20019>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: LinksApi#inventory_links_stats_flow\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
