=begin
#Telstra Programmable Network API

#Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.

OpenAPI spec version: 2.4.2
Contact: pnapi-support@team.telstra.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.1.2

=end

require 'uri'

module TelstraTPN
  class StatisticsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Get statistics for endpoint
    # Get statistics related to the specified endpoint
    # @param endpointuuid Unique identifier representing a specific endpoint
    # @param startdate Start date for statistics query
    # @param enddate End date for statistics query
    # @param [Hash] opts the optional parameters
    # @return [Array<InlineResponse20018>]
    def inventory_links_stats_endpoint(endpointuuid, startdate, enddate, opts = {})
      data, _status_code, _headers = inventory_links_stats_endpoint_with_http_info(endpointuuid, startdate, enddate, opts)
      data
    end

    # Get statistics for endpoint
    # Get statistics related to the specified endpoint
    # @param endpointuuid Unique identifier representing a specific endpoint
    # @param startdate Start date for statistics query
    # @param enddate End date for statistics query
    # @param [Hash] opts the optional parameters
    # @return [Array<(Array<InlineResponse20018>, Fixnum, Hash)>] Array<InlineResponse20018> data, response status code and response headers
    def inventory_links_stats_endpoint_with_http_info(endpointuuid, startdate, enddate, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: StatisticsApi.inventory_links_stats_endpoint ...'
      end
      # verify the required parameter 'endpointuuid' is set
      if @api_client.config.client_side_validation && endpointuuid.nil?
        fail ArgumentError, "Missing the required parameter 'endpointuuid' when calling StatisticsApi.inventory_links_stats_endpoint"
      end
      # verify the required parameter 'startdate' is set
      if @api_client.config.client_side_validation && startdate.nil?
        fail ArgumentError, "Missing the required parameter 'startdate' when calling StatisticsApi.inventory_links_stats_endpoint"
      end
      # verify the required parameter 'enddate' is set
      if @api_client.config.client_side_validation && enddate.nil?
        fail ArgumentError, "Missing the required parameter 'enddate' when calling StatisticsApi.inventory_links_stats_endpoint"
      end
      # resource path
      local_var_path = '/1.0.0/inventory/links-stats/endpoint/{endpointuuid}/{startdate}/{enddate}'.sub('{' + 'endpointuuid' + '}', endpointuuid.to_s).sub('{' + 'startdate' + '}', startdate.to_s).sub('{' + 'enddate' + '}', enddate.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['oAuth2']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<InlineResponse20018>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: StatisticsApi#inventory_links_stats_endpoint\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
    # Get state statistics for endpoint
    # Get statistics related to the state of the specified endpoint
    # @param endpointuuid Unique identifier representing a specific endpoint
    # @param startdate Start date for statistics query
    # @param enddate End date for statistics query
    # @param [Hash] opts the optional parameters
    # @return [Array<InlineResponse20020>]
    def inventory_links_stats_endpointstate(endpointuuid, startdate, enddate, opts = {})
      data, _status_code, _headers = inventory_links_stats_endpointstate_with_http_info(endpointuuid, startdate, enddate, opts)
      data
    end

    # Get state statistics for endpoint
    # Get statistics related to the state of the specified endpoint
    # @param endpointuuid Unique identifier representing a specific endpoint
    # @param startdate Start date for statistics query
    # @param enddate End date for statistics query
    # @param [Hash] opts the optional parameters
    # @return [Array<(Array<InlineResponse20020>, Fixnum, Hash)>] Array<InlineResponse20020> data, response status code and response headers
    def inventory_links_stats_endpointstate_with_http_info(endpointuuid, startdate, enddate, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: StatisticsApi.inventory_links_stats_endpointstate ...'
      end
      # verify the required parameter 'endpointuuid' is set
      if @api_client.config.client_side_validation && endpointuuid.nil?
        fail ArgumentError, "Missing the required parameter 'endpointuuid' when calling StatisticsApi.inventory_links_stats_endpointstate"
      end
      # verify the required parameter 'startdate' is set
      if @api_client.config.client_side_validation && startdate.nil?
        fail ArgumentError, "Missing the required parameter 'startdate' when calling StatisticsApi.inventory_links_stats_endpointstate"
      end
      # verify the required parameter 'enddate' is set
      if @api_client.config.client_side_validation && enddate.nil?
        fail ArgumentError, "Missing the required parameter 'enddate' when calling StatisticsApi.inventory_links_stats_endpointstate"
      end
      # resource path
      local_var_path = '/1.0.0/inventory/links-stats/endpointstate/{endpointuuid}/{startdate}/{enddate}'.sub('{' + 'endpointuuid' + '}', endpointuuid.to_s).sub('{' + 'startdate' + '}', startdate.to_s).sub('{' + 'enddate' + '}', enddate.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['oAuth2']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<InlineResponse20020>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: StatisticsApi#inventory_links_stats_endpointstate\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
    # Get statistics for flow
    # Get statistics related to the specified flow
    # @param linkid Unique identifier representing a specific link
    # @param startdate Start date for statistics query
    # @param enddate End date for statistics query
    # @param [Hash] opts the optional parameters
    # @return [Array<InlineResponse20019>]
    def inventory_links_stats_flow(linkid, startdate, enddate, opts = {})
      data, _status_code, _headers = inventory_links_stats_flow_with_http_info(linkid, startdate, enddate, opts)
      data
    end

    # Get statistics for flow
    # Get statistics related to the specified flow
    # @param linkid Unique identifier representing a specific link
    # @param startdate Start date for statistics query
    # @param enddate End date for statistics query
    # @param [Hash] opts the optional parameters
    # @return [Array<(Array<InlineResponse20019>, Fixnum, Hash)>] Array<InlineResponse20019> data, response status code and response headers
    def inventory_links_stats_flow_with_http_info(linkid, startdate, enddate, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: StatisticsApi.inventory_links_stats_flow ...'
      end
      # verify the required parameter 'linkid' is set
      if @api_client.config.client_side_validation && linkid.nil?
        fail ArgumentError, "Missing the required parameter 'linkid' when calling StatisticsApi.inventory_links_stats_flow"
      end
      # verify the required parameter 'startdate' is set
      if @api_client.config.client_side_validation && startdate.nil?
        fail ArgumentError, "Missing the required parameter 'startdate' when calling StatisticsApi.inventory_links_stats_flow"
      end
      # verify the required parameter 'enddate' is set
      if @api_client.config.client_side_validation && enddate.nil?
        fail ArgumentError, "Missing the required parameter 'enddate' when calling StatisticsApi.inventory_links_stats_flow"
      end
      # resource path
      local_var_path = '/1.0.0/inventory/links-stats/flow/{linkid}/{startdate}/{enddate}'.sub('{' + 'linkid' + '}', linkid.to_s).sub('{' + 'startdate' + '}', startdate.to_s).sub('{' + 'enddate' + '}', enddate.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['oAuth2']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<InlineResponse20019>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: StatisticsApi#inventory_links_stats_flow\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
