=begin
#Telstra Programmable Network API

#Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.

OpenAPI spec version: 2.1.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require "uri"

module TelstraTPN
  class VnfsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # List images in the Marketplace
    # List images in the Marketplace
    # @param [Hash] opts the optional parameters
    # @return [Model100MarketplaceImageResponse]
    def 100_marketplace_image_get(opts = {})
      data, _status_code, _headers = 100_marketplace_image_get_with_http_info(opts)
      return data
    end

    # List images in the Marketplace
    # List images in the Marketplace
    # @param [Hash] opts the optional parameters
    # @return [Array<(Model100MarketplaceImageResponse, Fixnum, Hash)>] Model100MarketplaceImageResponse data, response status code and response headers
    def 100_marketplace_image_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: VnfsApi.100_marketplace_image_get ..."
      end
      # resource path
      local_var_path = "/1.0.0/marketplace/image"

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Model100MarketplaceImageResponse')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: VnfsApi#100_marketplace_image_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
