=begin
#Telstra Programmable Network API

#Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.

OpenAPI spec version: 2.1.2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for TelstraTPN::EndpointsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'EndpointsApi' do
  before do
    # run before each test
    @instance = TelstraTPN::EndpointsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EndpointsApi' do
    it 'should create an instance of EndpointsApi' do
      expect(@instance).to be_instance_of(TelstraTPN::EndpointsApi)
    end
  end

  # unit tests for create_physical__port_endpoint
  # Create Physical (Port) Endpoint
  # Create Physical (Port) Endpoint
  # @param [Hash] opts the optional parameters
  # @option opts [Model100InventoryRegularendpointRequest] :body 
  # @return [Model100InventoryRegularendpointResponse]
  describe 'create_physical__port_endpoint test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_vnf_endpoint
  # Create VNF Endpoint
  # Create VNF Endpoint
  # @param [Hash] opts the optional parameters
  # @option opts [Model100InventoryVnfendpointRequest] :body 
  # @return [Model100InventoryVnfendpointResponse]
  describe 'create_vnf_endpoint test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_information_about_the_specified_endpoint
  # Get information about the specified endpoint
  # Get information about the specified endpoint
  # @param endpointuuid Unique identifier representing a specific endpoint
  # @param [Hash] opts the optional parameters
  # @return [Model100InventoryEndpointResponse]
  describe 'get_information_about_the_specified_endpoint test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_list_of_endpoints_for_a_customer
  # Get list of endpoints for a customer
  # Get list of endpoints for a customer
  # @param customeruuid Unique identifier representing a specific customer
  # @param [Hash] opts the optional parameters
  # @return [Model100InventoryEndpointsCustomeruuidResponse]
  describe 'get_list_of_endpoints_for_a_customer test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
