=begin
#Telstra Programmable Network API

#Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.

OpenAPI spec version: 2.1.2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for TelstraTPN::LinksApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LinksApi' do
  before do
    # run before each test
    @instance = TelstraTPN::LinksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LinksApi' do
    it 'should create an instance of LinksApi' do
      expect(@instance).to be_instance_of(TelstraTPN::LinksApi)
    end
  end

  # unit tests for create_link_and_initial_contract
  # Create Link and initial Contract
  # Create Link and initial Contract
  # @param [Hash] opts the optional parameters
  # @option opts [Model100InventoryLinkRequest] :body 
  # @return [Model100InventoryLinkResponse]
  describe 'create_link_and_initial_contract test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_active_links
  # Get active Links
  # Get active Links
  # @param customeruuid Unique identifier representing a specific customer
  # @param [Hash] opts the optional parameters
  # @return [Array<Link>]
  describe 'get_active_links test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_details_of_specified_link
  # Get details of specified link
  # Get details of specified link
  # @param linkid Unique identifier representing a specific link
  # @param [Hash] opts the optional parameters
  # @return [Model100InventoryLinksResponse]
  describe 'get_details_of_specified_link test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_link_history
  # Get Link history
  # Get Link history
  # @param linkid Unique identifier representing a specific link
  # @param [Hash] opts the optional parameters
  # @return [Model100InventoryLinksHistoryResponse]
  describe 'get_link_history test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
