=begin
#Telstra Programmable Network API

#Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.

OpenAPI spec version: 2.1.2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for TelstraTPN::TopologiesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TopologiesApi' do
  before do
    # run before each test
    @instance = TelstraTPN::TopologiesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TopologiesApi' do
    it 'should create an instance of TopologiesApi' do
      expect(@instance).to be_instance_of(TelstraTPN::TopologiesApi)
    end
  end

  # unit tests for create_a_named_topology_tag
  # Create a named topology tag
  # Create a named topology tag
  # @param [Hash] opts the optional parameters
  # @option opts [Ttms100TopologyTagRequest] :body 
  # @return [Topology]
  describe 'create_a_named_topology_tag test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_information_about_the_specified_topology_tag
  # Get information about the specified topology tag
  # Get information about the specified topology tag
  # @param topotaguuid Unique identifier representing a specific topology tag
  # @param [Hash] opts the optional parameters
  # @return [Topology]
  describe 'get_information_about_the_specified_topology_tag test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_all_topology_tags
  # List all topology tags
  # List all topology tags
  # @param [Hash] opts the optional parameters
  # @return [Array<Topology>]
  describe 'list_all_topology_tags test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_objects_for_topology
  # List objects for Topology
  # List all objects (Endpoints, Links, VPorts, etc.) associated with the topology tag.
  # @param topotaguuid Unique identifier representing a specific topology tag
  # @param [Hash] opts the optional parameters
  # @return [Ttms100TopologyTagObjectsResponse]
  describe 'list_objects_for_topology test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
